 version: "3"
 services:
  keycloak:
    container_name: pas_prod_keycloak    
    # command: ["-Djboss.http.port=8180"]
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=user 
      - KEYCLOAK_PASSWORD=user
      - DB_VENDOR=h2
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data/
    image: jboss/keycloak
 volumes:
  keycloak-data: 

