spring:
  main:
    allow-circular-references: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'


davincipct:
  datasource:
    url: 'jdbc:h2:file:./target/database/h2-davincipct'
    username: sa
    password: null
    driverClassName: org.h2.Driver
  # enforce_referential_integrity_on_delete: false
  # enforce_referential_integrity_on_write: false
  implementationguides:
    hl_7_fhir_us_davinci_pct:
      installMode: STORE_AND_INSTALL
      packageUrl: https://hl7.org/fhir/us/davinci-pct/2024May/package.tgz
      name: hl7.fhir.us.davinci-pct
      version: 2.0.0-ballot
      fetchDependencies: false
      reloadExisting: false
    uscore:
        url: http://hl7.org/fhir/us/core/STU3.1.1/package.tgz
        name: hl7.fhir.us.core
        version: 3.1.1
    hrex:
      url: http://hl7.org/fhir/us/davinci-hrex/package.tgz
      name: hl7.fhir.us.davinci-hrex
      version: 1.0.0
  



# davincipctcoordinationplatform:
#   datasource:
#     url: 'jdbc:h2:file:./target/database/h2-davincipctcoordinationplatform'
#     username: sa
#     password: null
#     driverClassName: org.h2.Driver
#   # enforce_referential_integrity_on_delete: false
#   # enforce_referential_integrity_on_write: false
#   implementationguides:
#     hl_7_fhir_us_davinci_pct:
#       installMode: STORE_ONLY
#       packageUrl: https://hl7.org/fhir/us/davinci-pct/2024May/package.tgz
#       name: hl7.fhir.us.davinci-pct
#       version: 2.0.0-ballot
#       fetchDependencies: false
#       reloadExisting: false

# davincipctcoordinationrequester:
#   datasource:
#     url: 'jdbc:h2:file:./target/database/h2-davincipctcoordinationrequester'
#     username: sa
#     password: null
#     driverClassName: org.h2.Driver
#   # enforce_referential_integrity_on_delete: false
#   # enforce_referential_integrity_on_write: false
#   implementationguides:
#     hl_7_fhir_us_davinci_pct:
#       installMode: STORE_ONLY
#       packageUrl: https://hl7.org/fhir/us/davinci-pct/2024May/package.tgz
#       name: hl7.fhir.us.davinci-pct
#       version: 2.0.0-ballot
#       fetchDependencies: false
#       reloadExisting: false

# davincipctgfecontributor:
#   datasource:
#     url: 'jdbc:h2:file:./target/database/h2-davincipctgfecontributor'
#     username: sa
#     password: null
#     driverClassName: org.h2.Driver
#   # enforce_referential_integrity_on_delete: false
#   # enforce_referential_integrity_on_write: false
#   implementationguides:
#     hl_7_fhir_us_davinci_pct:
#       installMode: STORE_ONLY
#       packageUrl: https://hl7.org/fhir/us/davinci-pct/2024May/package.tgz
#       name: hl7.fhir.us.davinci-pct
#       version: 2.0.0-ballot
#       fetchDependencies: false
#       reloadExisting: false


  allow_external_references: true
  allowed_bundle_types: COLLECTION,DOCUMENT,MESSAGE,TRANSACTION,TRANSACTIONRESPONSE,BATCH,BATCHRESPONSE,HISTORY,SEARCHSET
  # cors:
  #     allow_Credentials: true
  #     # These are allowed_origin patterns, see: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-
  #     allowed_origin:
  #       - '*'

  #   # Search coordinator thread pool sizes
  #   search-coord-core-pool-size: 20
  #   search-coord-max-pool-size: 100
  #   search-coord-queue-capacity: 200